[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Shortlister"
description = "Tool to assist with shortlisting applications"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = [
  "src/shortlister",
]
[tool.hatch.version]
